# データベース設定
useMySQL: false  # trueにするとMySQLを使用、falseならSQLiteを使用
mysql:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: "password"

# ロールバック設定
rollback:
  max-history: 5  # ロールバック履歴の最大保存数
  max-time: "1w" # ロールバックできる最大時間 (例えば1週間)
  max-players: 100  # 1回のロールバックで処理できる最大のプレイヤー数
  default-radius: -1  # -1は範囲制限なし
