name: CoiPlugin
version: 1.0-beta
main: com.example.Coi.CoiPlugin
author: Soryu-haruma(Asl, haruma9012kirby)
description: プレイヤーのインベントリを管理し、ロールバック機能を提供するプラグイン。
api: 1.21.1-R0.1-SNAPSHOT

commands:
  coi:
    description: プレイヤーのインベントリをロールバックするコマンド。
    usage: >
      /coi rollback t:[time] (optional: r:[radius] u:[player])
  coiundo:
    description: 前回のロールバックを取り消すコマンド。
    usage: /coi undo
permissions:
  coi.rollback:
    description: ロールバックコマンドを実行するための権限。
    default: op
  coi.undo:
    description: 前回のロールバックを取り消すための権限。
    default: op
