name: CoiPlugin
version: 1.0-beta
main: com.example.Coi.CoiPlugin
author: Soryu-haruma(Asl, haruma9012kirby)
description: プレイヤーのインベントリを管理し、ロールバック機能を提供するプラグイン。
api: 1.21.1-R0.1-SNAPSHOT

commands:
  coi:
    description: プレイヤーのインベントリをロールバックするコマンド。
  coiundo:
    description: プレイヤーのインベントリを元に戻すコマンド。
permissions:
  coi.rollback:
    description: ロールバックコマンドを実行するための権限。
    default: op
  coi.undo:
    description: 元に戻すコマンドを実行するための権限。
    default: op

